settings:
  username: "WardDeb"
  commit_msg: "Update README with the recent activity"
  readme_file: "./README.md"
  whitelisted_events:
    - create_repo
    - fork
    - issues_open
    - issues_close
    - pr_open
    - pr_merge
    - pr_close
    - release
  disabled_events:
    - "comments"
  date:
    text: "Last Updated: {DATE} (GMT)"
  messages:
    push: "ğŸ”¥ commited to {REPO}"
    issue_opened: "ğŸ”« Opened issue {ID} in {REPO}"
    issue_closed: "ğŸ¥¾ Closed issue {ID} in {REPO}"
    pr_opened: "ğŸª¢ Opened PR {ID} in {REPO}"
    pr_closed: "ğŸª¢ Closed PR {ID} in {REPO}"
    pr_merged: "ğŸª¢ Merged PR {ID} in {REPO}"
    create_repo: "ğŸ“” Created new repository {REPO}"
    new_release: "ğŸš€ Released {ID} in {REPO}"
