name: Activity
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Fetch latest activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: WardDeb/readme_and_act@main
        env:
          FILE_NAME: README.md
          GH_USERNAME: WardDeb
          MAX_LINES: 5
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
